### ISSUE TITLE
@tailwind base doesn't work

### ISSUE THREAD

**Issue by alexandr2110pro** [minagawah/cra-ts-emotion-tailwind-solution#2]
`@tailwind base` in the App.css in this example should actually add some basic css reset. But I can't see it in the result.

Would be glad if someone can explain why and how to fix that.

**Comment by minagawah** [comment]
@alexandr2110pro You are right. Thanks. I forgot the fact that I was dealing with CRA. It explicitly requires PostCSS loader configurations to load external CSS files. I made a fix, and it now seems to convert `@tailwind base` to normalize resets. I added `license-webpack-plugin` so that normalize license appears in the transformed styles when looking at embedded `<style>` elements with Chrome Dev Tools.
https://github.com/minagawah/cra-ts-emotion-tailwind-solution/commit/71fa9f7c6fab55560cdf716a1e437602c9e6fc0a
